name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up python 3.5
      uses: actions/setup-python@v3
      with: 
        python-version: 3.5
    - name: Install dependencies
      run: |
        make install
    - name: Linter
      run: |
        make lint
    - name: test
      run: |
        make test
